# Generated by Django 4.2.3 on 2023-07-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
    ]
