# Generated by Django 4.2.3 on 2023-07-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subheading',
            field=models.CharField(default='This is subheading', max_length=200),
        ),
    ]
