# Generated by Django 4.2.3 on 2023-08-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
