# Generated by Django 4.2.3 on 2023-08-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_delete_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('class1', models.CharField(max_length=200)),
                ('class2', models.CharField(max_length=200)),
                ('class3', models.CharField(max_length=200)),
            ],
        ),
    ]
